- name: Validar Servicio Instalado
  win_service:
    name: '{{ service_name }}'
  register: service_info
- name:
  debug:
    msg: '{{ service_info }}'

- name:
  debug:
    msg: "SERVICIO NO ENCONTRADO"
  when:   '{{ service_info.exists }} == false'